export const VEHICLE_MODELS = {
  "Abarth": ["124 Spider", "500", "595", "695", "Other"],
  "Alfa Romeo": ["Giulia", "Giulietta", "Stelvio", "Tonale", "Other"],
  "Aston Martin": ["DB11", "DBX", "Vantage", "DBS", "Other"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "TT", "e-tron", "Other"],
  "Bentley": ["Bentayga", "Continental GT", "Flying Spur", "Other"],
  "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "iX", "Other"],
  "Citroen": ["C1", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5 Aircross", "Berlingo", "Dispatch", "Other"],
  "Cupra": ["Ateca", "Born", "Formentor", "Leon", "Other"],
  "Dacia": ["Duster", "Jogger", "Sandero", "Spring", "Other"],
  "DS": ["DS 3", "DS 4", "DS 7", "DS 9", "Other"],
  "Ferrari": ["296 GTB", "812", "F8", "Portofino", "Roma", "SF90", "Other"],
  "Fiat": ["500", "500X", "Panda", "Tipo", "Doblo", "Other"],
  "Ford": ["Fiesta", "Focus", "Mondeo", "Puma", "Kuga", "Mustang", "Ranger", "Transit", "EcoSport", "Edge", "Galaxy", "S-Max", "Ka+", "Other"],
  "Honda": ["Civic", "CR-V", "HR-V", "Jazz", "e", "Other"],
  "Hyundai": ["i10", "i20", "i30", "Bayon", "Kona", "Tucson", "Santa Fe", "Ioniq 5", "Ioniq 6", "Other"],
  "Jaguar": ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF", "Other"],
  "Jeep": ["Avenger", "Compass", "Renegade", "Wrangler", "Grand Cherokee", "Other"],
  "Kia": ["Picanto", "Rio", "Ceed", "XCeed", "Stonic", "Niro", "Sportage", "Sorento", "EV6", "EV9", "Other"],
  "Lamborghini": ["Huracan", "Urus", "Aventador", "Other"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar", "Other"],
  "Lexus": ["CT", "IS", "ES", "LS", "UX", "NX", "RX", "LC", "Other"],
  "Lotus": ["Eletre", "Emira", "Evora", "Other"],
  "Maserati": ["Ghibli", "Levante", "MC20", "Quattroporte", "Grecale", "Other"],
  "Mazda": ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "CX-30", "CX-60", "MX-5", "MX-30", "Other"],
  "McLaren": ["540C", "570S", "720S", "Artura", "GT", "Other"],
  "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "CLA", "CLS", "E-Class", "S-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "Other"],
  "MG": ["MG3", "MG4", "MG5", "HS", "ZS", "Marvel R", "Other"],
  "MINI": ["Hatch", "Clubman", "Countryman", "Convertible", "Electric", "Other"],
  "Mitsubishi": ["Mirage", "ASX", "Eclipse Cross", "Outlander", "L200", "Other"],
  "Nissan": ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "GT-R", "Other"],
  "Peugeot": ["108", "208", "308", "508", "2008", "3008", "5008", "Rifter", "Partner", "e-208", "e-2008", "Other"],
  "Polestar": ["Polestar 2", "Polestar 3", "Other"],
  "Porsche": ["718", "911", "Taycan", "Panamera", "Macan", "Cayenne", "Other"],
  "Renault": ["Clio", "Captur", "Megane", "Kadjar", "Arkana", "Austral", "Zoe", "Megane E-Tech", "Other"],
  "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Spectre", "Other"],
  "SEAT": ["Ibiza", "Arona", "Leon", "Ateca", "Tarraco", "Other"],
  "Skoda": ["Citigo", "Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Other"],
  "Smart": ["EQ fortwo", "EQ forfour", "#1", "#3", "Other"],
  "SsangYong": ["Tivoli", "Korando", "Rexton", "Musso", "Other"],
  "Subaru": ["Impreza", "XV", "Forester", "Outback", "Levorg", "BRZ", "Other"],
  "Suzuki": ["Ignis", "Swift", "Baleno", "Vitara", "S-Cross", "Jimny", "Across", "Swace", "Other"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Other"],
  "Toyota": ["Aygo X", "Yaris", "Corolla", "Camry", "Prius", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Hilux", "Proace", "bZ4X", "Mirai", "GR Supra", "GT86", "Other"],
  "Vauxhall": ["Corsa", "Astra", "Insignia", "Crossland", "Grandland", "Mokka", "Combo", "Vivaro", "Corsa-e", "Mokka-e", "Other"],
  "Volkswagen": ["up!", "Polo", "Golf", "Arteon", "Passat", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Touran", "Sharan", "Caddy", "Transporter", "ID.3", "ID.4", "ID.5", "ID. Buzz", "Other"],
  "Volvo": ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "C40", "EX30", "EX90", "Other"],
  "Other": ["Other"]
};